// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type DiningDocumentDataSlicesSlice =
  | ReversedDestinationHighlightsSlice
  | DiningCtaSlice
  | ResonanceBlockSlice
  | IntroBlockSlice
  | HeroForOthersSlice;

/**
 * Content for Dining documents
 */
interface DiningDocumentData {
  /**
   * Slice Zone field in *Dining*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: dining.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<DiningDocumentDataSlicesSlice> /**
   * Meta Title field in *Dining*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: dining.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Dining*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: dining.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Dining*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dining.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Dining document from Prismic
 *
 * - **API ID**: `dining`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DiningDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DiningDocumentData>,
    "dining",
    Lang
  >;

/**
 * Item in *Header Settings → Navigation*
 */
export interface HeaderSettingsDocumentDataNavigationItem {
  /**
   * Link field in *Header Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Link Lable field in *Header Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.navigation[].link_lable
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_lable: prismic.KeyTextField;
}

/**
 * Content for Header Settings documents
 */
interface HeaderSettingsDocumentData {
  /**
   * Site Title field in *Header Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Header Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Header Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Header Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<
    Simplify<HeaderSettingsDocumentDataNavigationItem>
  >;

  /**
   * Nav Button-Link field in *Header Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.nav_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Nav Button-Link Text field in *Header Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_settings.nav_buttonlink_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_buttonlink_text: prismic.KeyTextField;
}

/**
 * Header Settings document from Prismic
 *
 * - **API ID**: `header_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderSettingsDocumentData>,
    "header_settings",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | ReversedDestinationHighlightsSlice
  | TestimonialsSlice
  | BanquetHallsSlice
  | TaglineHeroSliceSlice
  | RoomShowcaseSliceSlice
  | DestinationHighlightSlice
  | MeetingHallsSlice
  | OneWithSideWordsSlice
  | HeroSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | DiningDocument
  | HeaderSettingsDocument
  | HomepageDocument;

/**
 * Primary content in *BanquetHalls → Default → Primary*
 */
export interface BanquetHallsSliceDefaultPrimary {
  /**
   * Banquet Image field in *BanquetHalls → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banquet_halls.default.primary.banquet_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  banquet_image: prismic.ImageField<never>;

  /**
   * Heading field in *BanquetHalls → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banquet_halls.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *BanquetHalls → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banquet_halls.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Link field in *BanquetHalls → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banquet_halls.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *BanquetHalls → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banquet_halls.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for BanquetHalls Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BanquetHallsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BanquetHallsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BanquetHalls*
 */
type BanquetHallsSliceVariation = BanquetHallsSliceDefault;

/**
 * BanquetHalls Shared Slice
 *
 * - **API ID**: `banquet_halls`
 * - **Description**: BanquetHalls
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BanquetHallsSlice = prismic.SharedSlice<
  "banquet_halls",
  BanquetHallsSliceVariation
>;

/**
 * Primary content in *DestinationHighlight → Default → Primary*
 */
export interface DestinationHighlightSliceDefaultPrimary {
  /**
   * Heading field in *DestinationHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_highlight.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *DestinationHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_highlight.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Explore Button field in *DestinationHighlight → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_highlight.default.primary.explore_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  explore_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *DestinationHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_highlight.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Image field in *DestinationHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_highlight.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Link field in *DestinationHighlight → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_highlight.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_link: prismic.KeyTextField;

  /**
   * Video field in *DestinationHighlight → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: destination_highlight.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video: prismic.BooleanField;
}

/**
 * Default variation for DestinationHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DestinationHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DestinationHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DestinationHighlight*
 */
type DestinationHighlightSliceVariation = DestinationHighlightSliceDefault;

/**
 * DestinationHighlight Shared Slice
 *
 * - **API ID**: `destination_highlight`
 * - **Description**: DestinationHighlight
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DestinationHighlightSlice = prismic.SharedSlice<
  "destination_highlight",
  DestinationHighlightSliceVariation
>;

/**
 * Default variation for DestinationHighlightSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DestinationHighlightSliceSliceDefault =
  prismic.SharedSliceVariation<"default", Record<string, never>, never>;

/**
 * Slice variation for *DestinationHighlightSlice*
 */
type DestinationHighlightSliceSliceVariation =
  DestinationHighlightSliceSliceDefault;

/**
 * DestinationHighlightSlice Shared Slice
 *
 * - **API ID**: `destination_highlight_slice`
 * - **Description**: DestinationHighlightSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DestinationHighlightSliceSlice = prismic.SharedSlice<
  "destination_highlight_slice",
  DestinationHighlightSliceSliceVariation
>;

/**
 * Item in *DiningCta → Default → Primary → Parallax*
 */
export interface DiningCtaSliceDefaultPrimaryParallaxItem {
  /**
   * Parallax Images field in *DiningCta → Default → Primary → Parallax*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dining_cta.default.primary.parallax[].parallax_images
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  parallax_images: prismic.ImageField<never>;
}

/**
 * Primary content in *DiningCta → Default → Primary*
 */
export interface DiningCtaSliceDefaultPrimary {
  /**
   * Heading field in *DiningCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dining_cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *DiningCta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dining_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Link field in *DiningCta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: dining_cta.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *DiningCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dining_cta.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Image One field in *DiningCta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dining_cta.default.primary.image_one
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_one: prismic.ImageField<never>;

  /**
   * Parallax field in *DiningCta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: dining_cta.default.primary.parallax[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  parallax: prismic.GroupField<
    Simplify<DiningCtaSliceDefaultPrimaryParallaxItem>
  >;
}

/**
 * Default variation for DiningCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DiningCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DiningCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DiningCta*
 */
type DiningCtaSliceVariation = DiningCtaSliceDefault;

/**
 * DiningCta Shared Slice
 *
 * - **API ID**: `dining_cta`
 * - **Description**: DiningCta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DiningCtaSlice = prismic.SharedSlice<
  "dining_cta",
  DiningCtaSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Carousel*
 */
export interface HeroSliceDefaultPrimaryCarouselItem {
  /**
   * Image field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * YouTube Video ID field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].youtube_video_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  youtube_video_id: prismic.KeyTextField;

  /**
   * Video  field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.carousel[].video
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video: prismic.BooleanField;

  /**
   * thumbnail field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].thumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Carousel field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCarouselItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HeroForOthers → Default → Primary*
 */
export interface HeroForOthersSliceDefaultPrimary {
  /**
   * Hero Image field in *HeroForOthers → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_for_others.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero Heading field in *HeroForOthers → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_for_others.default.primary.hero_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_heading: prismic.RichTextField;
}

/**
 * Default variation for HeroForOthers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroForOthersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroForOthersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroForOthers*
 */
type HeroForOthersSliceVariation = HeroForOthersSliceDefault;

/**
 * HeroForOthers Shared Slice
 *
 * - **API ID**: `hero_for_others`
 * - **Description**: HeroForOthers
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroForOthersSlice = prismic.SharedSlice<
  "hero_for_others",
  HeroForOthersSliceVariation
>;

/**
 * Primary content in *IntroBlock → Default → Primary*
 */
export interface IntroBlockSliceDefaultPrimary {
  /**
   * Heading field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Link field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *IntroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_block.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for IntroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroBlock*
 */
type IntroBlockSliceVariation = IntroBlockSliceDefault;

/**
 * IntroBlock Shared Slice
 *
 * - **API ID**: `intro_block`
 * - **Description**: IntroBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroBlockSlice = prismic.SharedSlice<
  "intro_block",
  IntroBlockSliceVariation
>;

/**
 * Item in *MeetingHalls → Default → Primary → Rooms*
 */
export interface MeetingHallsSliceDefaultPrimaryRoomsItem {
  /**
   * Image field in *MeetingHalls → Default → Primary → Rooms*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meeting_halls.default.primary.rooms[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Card Title field in *MeetingHalls → Default → Primary → Rooms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meeting_halls.default.primary.rooms[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card Description field in *MeetingHalls → Default → Primary → Rooms*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meeting_halls.default.primary.rooms[].card_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_description: prismic.KeyTextField;

  /**
   * Room Link field in *MeetingHalls → Default → Primary → Rooms*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: meeting_halls.default.primary.rooms[].room_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  room_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *MeetingHalls → Default → Primary*
 */
export interface MeetingHallsSliceDefaultPrimary {
  /**
   * Heading field in *MeetingHalls → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meeting_halls.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MeetingHalls → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meeting_halls.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Rooms field in *MeetingHalls → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: meeting_halls.default.primary.rooms[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  rooms: prismic.GroupField<Simplify<MeetingHallsSliceDefaultPrimaryRoomsItem>>;
}

/**
 * Default variation for MeetingHalls Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MeetingHallsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MeetingHallsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MeetingHalls*
 */
type MeetingHallsSliceVariation = MeetingHallsSliceDefault;

/**
 * MeetingHalls Shared Slice
 *
 * - **API ID**: `meeting_halls`
 * - **Description**: MeetingHalls
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MeetingHallsSlice = prismic.SharedSlice<
  "meeting_halls",
  MeetingHallsSliceVariation
>;

/**
 * Primary content in *OneWithSideWords → Default → Primary*
 */
export interface OneWithSideWordsSliceDefaultPrimary {
  /**
   * Top Sentence field in *OneWithSideWords → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_with_side_words.default.primary.top_sentence
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  top_sentence: prismic.RichTextField;

  /**
   * Left Word field in *OneWithSideWords → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_with_side_words.default.primary.left_word
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  left_word: prismic.RichTextField;

  /**
   * Right Word field in *OneWithSideWords → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_with_side_words.default.primary.right_word
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  right_word: prismic.RichTextField;

  /**
   * Description field in *OneWithSideWords → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_with_side_words.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Button field in *OneWithSideWords → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: one_with_side_words.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Video field in *OneWithSideWords → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_with_side_words.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video: prismic.KeyTextField;
}

/**
 * Default variation for OneWithSideWords Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OneWithSideWordsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OneWithSideWordsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OneWithSideWords*
 */
type OneWithSideWordsSliceVariation = OneWithSideWordsSliceDefault;

/**
 * OneWithSideWords Shared Slice
 *
 * - **API ID**: `one_with_side_words`
 * - **Description**: OneWithSideWords
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OneWithSideWordsSlice = prismic.SharedSlice<
  "one_with_side_words",
  OneWithSideWordsSliceVariation
>;

/**
 * Primary content in *ResonanceBlock → Default → Primary*
 */
export interface ResonanceBlockSliceDefaultPrimary {
  /**
   * Horizontal Image field in *ResonanceBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resonance_block.default.primary.horizontal_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  horizontal_image: prismic.ImageField<never>;

  /**
   * Horizontal Image Text field in *ResonanceBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resonance_block.default.primary.horizontal_image_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  horizontal_image_text: prismic.RichTextField;

  /**
   * Vertical Image field in *ResonanceBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resonance_block.default.primary.vertical_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  vertical_image: prismic.ImageField<never>;
}

/**
 * Default variation for ResonanceBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResonanceBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResonanceBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ResonanceBlock*
 */
type ResonanceBlockSliceVariation = ResonanceBlockSliceDefault;

/**
 * ResonanceBlock Shared Slice
 *
 * - **API ID**: `resonance_block`
 * - **Description**: ResonanceBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResonanceBlockSlice = prismic.SharedSlice<
  "resonance_block",
  ResonanceBlockSliceVariation
>;

/**
 * Primary content in *ReversedDestinationHighlights → Default → Primary*
 */
export interface ReversedDestinationHighlightsSliceDefaultPrimary {
  /**
   * Heading field in *ReversedDestinationHighlights → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reversed_destination_highlights.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ReversedDestinationHighlights → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reversed_destination_highlights.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Link field in *ReversedDestinationHighlights → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: reversed_destination_highlights.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *ReversedDestinationHighlights → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reversed_destination_highlights.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Image field in *ReversedDestinationHighlights → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reversed_destination_highlights.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video ID field in *ReversedDestinationHighlights → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reversed_destination_highlights.default.primary.video_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_id: prismic.KeyTextField;

  /**
   * Video field in *ReversedDestinationHighlights → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: reversed_destination_highlights.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video: prismic.BooleanField;
}

/**
 * Default variation for ReversedDestinationHighlights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReversedDestinationHighlightsSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ReversedDestinationHighlightsSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *ReversedDestinationHighlights*
 */
type ReversedDestinationHighlightsSliceVariation =
  ReversedDestinationHighlightsSliceDefault;

/**
 * ReversedDestinationHighlights Shared Slice
 *
 * - **API ID**: `reversed_destination_highlights`
 * - **Description**: ReversedDestinationHighlights
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReversedDestinationHighlightsSlice = prismic.SharedSlice<
  "reversed_destination_highlights",
  ReversedDestinationHighlightsSliceVariation
>;

/**
 * Item in *RoomShowcaseSlice → Default → Primary → Room Card*
 */
export interface RoomShowcaseSliceSliceDefaultPrimaryRoomCardItem {
  /**
   * Image field in *RoomShowcaseSlice → Default → Primary → Room Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: room_showcase_slice.default.primary.room_card[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *RoomShowcaseSlice → Default → Primary → Room Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room_showcase_slice.default.primary.room_card[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *RoomShowcaseSlice → Default → Primary → Room Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room_showcase_slice.default.primary.room_card[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *RoomShowcaseSlice → Default → Primary → Room Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: room_showcase_slice.default.primary.room_card[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *RoomShowcaseSlice → Default → Primary*
 */
export interface RoomShowcaseSliceSliceDefaultPrimary {
  /**
   * Room Card field in *RoomShowcaseSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: room_showcase_slice.default.primary.room_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  room_card: prismic.GroupField<
    Simplify<RoomShowcaseSliceSliceDefaultPrimaryRoomCardItem>
  >;
}

/**
 * Default variation for RoomShowcaseSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomShowcaseSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoomShowcaseSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RoomShowcaseSlice*
 */
type RoomShowcaseSliceSliceVariation = RoomShowcaseSliceSliceDefault;

/**
 * RoomShowcaseSlice Shared Slice
 *
 * - **API ID**: `room_showcase_slice`
 * - **Description**: RoomShowcaseSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RoomShowcaseSliceSlice = prismic.SharedSlice<
  "room_showcase_slice",
  RoomShowcaseSliceSliceVariation
>;

/**
 * Item in *TaglineHeroSlice → Repeatable Field Variation → Primary → Footer CTA*
 */
export interface TaglineHeroSliceSliceRepeatableFieldVariationPrimaryFooterCtaItem {
  /**
   * TextOne field in *TaglineHeroSlice → Repeatable Field Variation → Primary → Footer CTA*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.repeatableFieldVariation.primary.footer_cta[].textone
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textone: prismic.RichTextField;

  /**
   * ImgVidOne field in *TaglineHeroSlice → Repeatable Field Variation → Primary → Footer CTA*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.repeatableFieldVariation.primary.footer_cta[].imgvidone
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imgvidone: prismic.ImageField<never>;

  /**
   * VideoLink field in *TaglineHeroSlice → Repeatable Field Variation → Primary → Footer CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.repeatableFieldVariation.primary.footer_cta[].videolink
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  videolink: prismic.KeyTextField;

  /**
   * Video Toggle field in *TaglineHeroSlice → Repeatable Field Variation → Primary → Footer CTA*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tagline_hero_slice.repeatableFieldVariation.primary.footer_cta[].video_toggle
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video_toggle: prismic.BooleanField;

  /**
   * Video Thumbnail field in *TaglineHeroSlice → Repeatable Field Variation → Primary → Footer CTA*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.repeatableFieldVariation.primary.footer_cta[].video_thumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  video_thumbnail: prismic.ImageField<never>;

  /**
   * TextTwo field in *TaglineHeroSlice → Repeatable Field Variation → Primary → Footer CTA*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.repeatableFieldVariation.primary.footer_cta[].texttwo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texttwo: prismic.RichTextField;
}

/**
 * Primary content in *TaglineHeroSlice → Default → Primary*
 */
export interface TaglineHeroSliceSliceDefaultPrimary {
  /**
   * TextFieldOne field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.textfieldone
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textfieldone: prismic.RichTextField;

  /**
   * ImgVidOne field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.imgvidone
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imgvidone: prismic.ImageField<never>;

  /**
   * VideoLinkOne field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.videolinkone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  videolinkone: prismic.KeyTextField;

  /**
   * Video field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tagline_hero_slice.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video: prismic.BooleanField;

  /**
   * VideoOneThumbnail field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.videoonethumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  videoonethumbnail: prismic.ImageField<never>;

  /**
   * TextFieldTwo field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.textfieldtwo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textfieldtwo: prismic.RichTextField;

  /**
   * TextFieldThree field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.textfieldthree
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textfieldthree: prismic.RichTextField;

  /**
   * ImgVidTwo field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.imgvidtwo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imgvidtwo: prismic.ImageField<never>;

  /**
   * VideoLinkTwo field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.videolinktwo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  videolinktwo: prismic.KeyTextField;

  /**
   * VideoTwo field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tagline_hero_slice.default.primary.videotwo
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  videotwo: prismic.BooleanField;

  /**
   * VideoTwoThumbnail field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.videotwothumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  videotwothumbnail: prismic.ImageField<never>;

  /**
   * TextFieldFour field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.textfieldfour
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textfieldfour: prismic.RichTextField;

  /**
   * TextFieldFive field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.textfieldfive
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textfieldfive: prismic.RichTextField;

  /**
   * ImgVidThree field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.imgvidthree
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imgvidthree: prismic.ImageField<never>;

  /**
   * VideoLinkThree field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.videolinkthree
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  videolinkthree: prismic.KeyTextField;

  /**
   * VideoThree field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tagline_hero_slice.default.primary.videothree
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  videothree: prismic.BooleanField;

  /**
   * VideoThreeThumbnail field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.videothreethumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  videothreethumbnail: prismic.ImageField<never>;

  /**
   * TextFieldSix field in *TaglineHeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.default.primary.textfieldsix
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  textfieldsix: prismic.RichTextField;
}

/**
 * Default variation for TaglineHeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TaglineHeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TaglineHeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TaglineHeroSlice → Repeatable Field Variation → Primary*
 */
export interface TaglineHeroSliceSliceRepeatableFieldVariationPrimary {
  /**
   * Footer CTA field in *TaglineHeroSlice → Repeatable Field Variation → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tagline_hero_slice.repeatableFieldVariation.primary.footer_cta[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_cta: prismic.GroupField<
    Simplify<TaglineHeroSliceSliceRepeatableFieldVariationPrimaryFooterCtaItem>
  >;
}

/**
 * Repeatable Field Variation variation for TaglineHeroSlice Slice
 *
 * - **API ID**: `repeatableFieldVariation`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TaglineHeroSliceSliceRepeatableFieldVariation =
  prismic.SharedSliceVariation<
    "repeatableFieldVariation",
    Simplify<TaglineHeroSliceSliceRepeatableFieldVariationPrimary>,
    never
  >;

/**
 * tag variation for TaglineHeroSlice Slice
 *
 * - **API ID**: `tag`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TaglineHeroSliceSliceTag = prismic.SharedSliceVariation<
  "tag",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TaglineHeroSlice*
 */
type TaglineHeroSliceSliceVariation =
  | TaglineHeroSliceSliceDefault
  | TaglineHeroSliceSliceRepeatableFieldVariation
  | TaglineHeroSliceSliceTag;

/**
 * TaglineHeroSlice Shared Slice
 *
 * - **API ID**: `tagline_hero_slice`
 * - **Description**: TaglineHeroSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TaglineHeroSliceSlice = prismic.SharedSlice<
  "tagline_hero_slice",
  TaglineHeroSliceSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Quote field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DiningDocument,
      DiningDocumentData,
      DiningDocumentDataSlicesSlice,
      HeaderSettingsDocument,
      HeaderSettingsDocumentData,
      HeaderSettingsDocumentDataNavigationItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BanquetHallsSlice,
      BanquetHallsSliceDefaultPrimary,
      BanquetHallsSliceVariation,
      BanquetHallsSliceDefault,
      DestinationHighlightSlice,
      DestinationHighlightSliceDefaultPrimary,
      DestinationHighlightSliceVariation,
      DestinationHighlightSliceDefault,
      DestinationHighlightSliceSlice,
      DestinationHighlightSliceSliceVariation,
      DestinationHighlightSliceSliceDefault,
      DiningCtaSlice,
      DiningCtaSliceDefaultPrimaryParallaxItem,
      DiningCtaSliceDefaultPrimary,
      DiningCtaSliceVariation,
      DiningCtaSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryCarouselItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroForOthersSlice,
      HeroForOthersSliceDefaultPrimary,
      HeroForOthersSliceVariation,
      HeroForOthersSliceDefault,
      IntroBlockSlice,
      IntroBlockSliceDefaultPrimary,
      IntroBlockSliceVariation,
      IntroBlockSliceDefault,
      MeetingHallsSlice,
      MeetingHallsSliceDefaultPrimaryRoomsItem,
      MeetingHallsSliceDefaultPrimary,
      MeetingHallsSliceVariation,
      MeetingHallsSliceDefault,
      OneWithSideWordsSlice,
      OneWithSideWordsSliceDefaultPrimary,
      OneWithSideWordsSliceVariation,
      OneWithSideWordsSliceDefault,
      ResonanceBlockSlice,
      ResonanceBlockSliceDefaultPrimary,
      ResonanceBlockSliceVariation,
      ResonanceBlockSliceDefault,
      ReversedDestinationHighlightsSlice,
      ReversedDestinationHighlightsSliceDefaultPrimary,
      ReversedDestinationHighlightsSliceVariation,
      ReversedDestinationHighlightsSliceDefault,
      RoomShowcaseSliceSlice,
      RoomShowcaseSliceSliceDefaultPrimaryRoomCardItem,
      RoomShowcaseSliceSliceDefaultPrimary,
      RoomShowcaseSliceSliceVariation,
      RoomShowcaseSliceSliceDefault,
      TaglineHeroSliceSlice,
      TaglineHeroSliceSliceDefaultPrimary,
      TaglineHeroSliceSliceRepeatableFieldVariationPrimaryFooterCtaItem,
      TaglineHeroSliceSliceRepeatableFieldVariationPrimary,
      TaglineHeroSliceSliceVariation,
      TaglineHeroSliceSliceDefault,
      TaglineHeroSliceSliceRepeatableFieldVariation,
      TaglineHeroSliceSliceTag,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
