import { EB_Garamond } from "next/font/google";
import "./globals.css";
import SmoothScrollWrapper from "./components/SmoothScrollWrapper";

const garamond = EB_Garamond({
  variable: "--font-eb-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"], // <-- include italic
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${garamond.variable}  antialiased`}>
        <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
      </body>
    </html>
  );
}
