import { EB_Garamond, Barlow_Semi_Condensed, Barlow } from "next/font/google";
import "./globals.css";
import SmoothScrollWrapper from "../components/SmoothScrollWrapper";
import Header from "@/components/HeaderWrapper";
import FooterServer from "@/components/FooterServer";
import LenisScrollProvider from "@/components/LenisScrollContext";
import { Toaster } from "react-hot-toast";
import WebVitals from "@/components/WebVitals";
import SnowEasterEggClient from "@/components/SnowEasterEggClient";
import HotelJsonLd from "@/components/HotelJsonLd";
import GoogleAnalytics from "@/components/GoogleAnalytics";
import { LoaderProvider } from "@/context/LoaderContext";

const garamond = EB_Garamond({
  variable: "--font-eb-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"], // <-- include italic
  display: "swap",
});

const barlow = Barlow_Semi_Condensed({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"], // <-- include italic
  display: "swap",
});
const barlowNormal = Barlow({
  variable: "--font-barlowNormal",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"], // <-- include italic
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  // maximumScale: 1,
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://images.prismic.io"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${garamond.variable} ${barlow.variable} ${barlowNormal.variable}  antialiased`}
      >
        {/* GA4 Google tag — requires NEXT_PUBLIC_GA_MEASUREMENT_ID */}
        <GoogleAnalytics />
        {/* Hotel entity for search / local discovery — not visible in the UI */}
        <HotelJsonLd />
        <SnowEasterEggClient />
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 3000,
            style: {
              background: "transparent",
              padding: 0,
              border: "none",
            },
          }}
        />
        {/* <WebVitals /> */}
        <LenisScrollProvider>
          <Header />
          <LoaderProvider>
            <main id="main-content">{children}</main>
          </LoaderProvider>
          <FooterServer />
        </LenisScrollProvider>
      </body>
    </html>
  );
}
