import { EB_Garamond, Barlow_Semi_Condensed, Barlow } from "next/font/google";
import "./globals.css";
import SmoothScrollWrapper from "../components/SmoothScrollWrapper";
import Header from "@/components/HeaderWrapper";
import FooterServer from "@/components/FooterServer";
import LenisScrollProvider from "@/components/LenisScrollContext";

const garamond = EB_Garamond({
  variable: "--font-eb-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"], // <-- include italic
  display: "swap",
});

const barlow = Barlow_Semi_Condensed({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"], // <-- include italic
  display: "swap",
});
const barlowNormal = Barlow({
  variable: "--font-barlowNormal",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"], // <-- include italic
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${garamond.variable} ${barlow.variable} ${barlowNormal.variable}  antialiased`}
      >
        <LenisScrollProvider>
          <Header />
          {children}
          <FooterServer />
        </LenisScrollProvider>
      </body>
    </html>
  );
}
