// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banquet_halls: dynamic(() => import("./BanquetHalls")),
  destination_highlight: dynamic(() => import("./DestinationHighlight")),
  destination_highlight_slice: dynamic(
    () => import("./DestinationHighlightSlice"),
  ),
  hero: dynamic(() => import("./Hero")),
  hero_for_others: dynamic(() => import("./HeroForOthers")),
  intro_block: dynamic(() => import("./IntroBlock")),
  meeting_halls: dynamic(() => import("./MeetingHalls")),
  one_with_side_words: dynamic(() => import("./OneWithSideWords")),
  room_showcase_slice: dynamic(() => import("./RoomShowcaseSlice")),
  tagline_hero_slice: dynamic(() => import("./TaglineHeroSlice")),
  testimonials: dynamic(() => import("./Testimonials")),
};
