// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_the_room: dynamic(() => import("./AboutTheRoom")),
  amenities: dynamic(() => import("./Amenities")),
  banquet_halls: dynamic(() => import("./BanquetHalls")),
  call_to_action_banner: dynamic(() => import("./CallToActionBanner")),
  destination_highlight: dynamic(() => import("./DestinationHighlight")),
  destination_highlight_slice: dynamic(
    () => import("./DestinationHighlightSlice"),
  ),
  dining_cta: dynamic(() => import("./DiningCta")),
  discover_hero: dynamic(() => import("./DiscoverHero")),
  full_image: dynamic(() => import("./FullImage")),
  hero: dynamic(() => import("./Hero")),
  hero_for_others: dynamic(() => import("./HeroForOthers")),
  hero_intro_slice: dynamic(() => import("./HeroIntroSlice")),
  intro_block: dynamic(() => import("./IntroBlock")),
  location_and_contacts: dynamic(() => import("./LocationAndContacts")),
  meeting_halls: dynamic(() => import("./MeetingHalls")),
  one_with_side_words: dynamic(() => import("./OneWithSideWords")),
  our_story_intro: dynamic(() => import("./StoryBlockA")),
  picture_section: dynamic(() => import("./PictureSection")),
  placesto_visit: dynamic(() => import("./PlacestoVisit")),
  resonance_block: dynamic(() => import("./ResonanceBlock")),
  reversed_destination_highlights: dynamic(
    () => import("./ReversedDestinationHighlights"),
  ),
  room_showcase_slice: dynamic(() => import("./RoomShowcaseSlice")),
  scroll_section: dynamic(() => import("./ScrollSection")),
  story_block_b: dynamic(() => import("./StoryBlockB")),
  story_block_c: dynamic(() => import("./StoryBlockC")),
  story_block_d: dynamic(() => import("./StoryBlockD")),
  tagline_hero_slice: dynamic(() => import("./TaglineHeroSlice")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_and_dot_wave: dynamic(() => import("./TextAndDotWave")),
  tips_explore: dynamic(() => import("./TipsExplore")),
};
